name: LLM Issue Response
on:
  issues:
    types: [opened]

jobs:
  respond-with-llm:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub ibm-watson-machine-learning
          
      - name: Process Issue with LLM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IBM_CLOUD_API_KEY: ${{secrets.IBM_CLOUD_API_KEY}}
          IBM_PROJECT_ID: ${{secrets.IBM_PROJECT_ID}}
        run: |
          python .github/scripts/process-issue.py